---
- hosts: all
  remote_user: doug
  vars:
    -remote_password: "H0onglam"
  tasks: 
   - name: copy stuff to r2391
     copy: src=/home/dc/hadoop-benchmarks/perf.sh dest=/home/doug/perf.sh 
  #test shell
   - name: test bash command
     command: bash -c "/home/doug/perf.sh initlog"
  # test java
   - name: test java 
     command: bash -c "/home/doug/hadoop-benchmarks/perf.sh testjava"
   - name: hadoop
     sudo: yes
     sudo_user: root --ask-sudo-pass
     command: bash -c "/home/doug/hadoop-benchmarks/perf.sh installhadoop"
