---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
 
  tasks: 
   - name: add user to sudo
     lineinfile: dest=/home/dc/hadoop-benchmarks/sudoers  line="doug    ALL=(ALL)       ALL"  insertafter="root\tALL" 
