---
- hosts: all
  remote_user: root

  tasks: 
   - name: copy orig sudo to a backup
     command: cp -f /etc/sudoers /etc/sudoers.backup

   - name: add user to sudo
     lineinfile: dest=/etc/sudoers backup=yes state=present regex='^root' line='asdf'
