
---
- hosts: all
  su: yes
  su_user: root
  remote_user: doug
  
  tasks: 
   - name: copy public key to remote hosts
     authorized_key: user=doug key="{{ lookup('file','~/.ssh/id_rsa.pub') }}" state=present manage_dir=yes
                      
   - name: copy nopasswd sudoers
     command: 'scp sudoers.fix root@r2391-d5-us01:/etc/sudoers'
